version: '3'

services: 
  electricity:
    build: .
    environment:
      - token=${reeToken}
  elastic:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.5.2
    container_name: elastic
    environment:
      - node.name=elastic
      - cluster.name=elasticsearch_cluster
      - cluster.initial_master_nodes=elastic
      - bootstrap.memory_lock=true
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
      - discovery.type=single-node
    ulimits:
      memlock:
        soft: -1
        hard: -1
    volumes:
      - ./elastic_data:/usr/share/elasticsearch/data
    ports:
      - 9200:9200
  elastichq:
    image: elastichq/elasticsearch-hq:latest
    ports:
      - 80:5000